version: '3.9'

services:
  ros:
    build: .
    command: ['tail', '-f', '/dev/null']
    ports:
      - '11311:11311'
      - '5999:6000'
    environment:
      - XAUTHORITY=/.Xauthority
      - DISPLAY=${IP}:0
    volumes:
      - './src:/root/catkin_ws/src'
      - '/tmp/.X11-unix:/tmp/.X11-unix'
      - '~/.Xauthority:/.Xauthority'
